name: Build and Deploy Backend

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup JDK
        uses: actions/setup-java@v3
        with: 
          java-version: 17
          distribution: 'temurin'

      - name: Build JAR
        run: mvn clean package -DskipTests

      - name: Docker Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Buil Docker Image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/prerequisite-course-identifier-backend:latest .

      - name: Push Docker Image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/prerequisite-course-identifier-backend:latest
      
      - name: Render Deployment
        run: |
            curl --request POST \
            --url https://api.render.com/v1/services/srv-ctnksmtsvqrc73b278g0/deploys \
            --header 'accept: application/json' \
            --header "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}"
